### ISSUE TITLE
focusables

### ISSUE THREAD

**Issue by scottaohara** [lloydi/WTFocus#2]
the focusables const contains the details element, but that element is not focusable, so that can probably be removed - unless you have it there for reasons I'm unaware?

also, i've seen various instances of tabindex="-NumberOtherThan1"

maybe the tabindex selector could be changed to `tabindex^="-"` so it'll catch all negative values, rather than just -1?

**Comment by lloydi** [comment]
Good catch. Will sort that v soon.

**Comment by lloydi** [comment]
A nice easy fix, eh? Like it, like it.
